apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: emp-frontend-claim1
  name: emp-frontend-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
