apiVersion: v1
kind: Service
metadata:
  labels:
    app: emp-frontend
  name: emp-frontend
spec:
  type: NodePort
  clusterIP: 10.96.0.14
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: emp-frontend
