apiVersion: v1
kind: Service
metadata:
  labels:
    app: emp-frontend
  name: emp-frontend
spec:
  type: LoadBalancer
  clusterIP: 10.96.0.14
  externalIPs:
    - 192.168.100.14
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: emp-frontend
