services:
  jenkins_app:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - jenkins
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
      - "${DOCKER_PATH}:/usr/bin/docker"
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true
    privileged: true
volumes:
  jenkins-docker-certs:
  jenkins-data:
networks:
  jenkins:
#DOCKER_PATH=$(which docker) docker compose up
