services:
  mysqldb:
    image: "khanster/mysql:latest"
    restart: always
    networks:
      - angular
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: ecommerce_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
networks:
  angular:
    name: angular
    external: true

