apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysqldb
  name: mysqldb
spec:
  type: LoadBalancer
  clusterIP: 10.96.0.11
  externalIPs:
    - 192.168.0.11
  externalTrafficPolicy: Local
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app: mysqldb
