apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysqldb
  name: mysqldb
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mysqldb
