apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: emp-backend
  name: emp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emp-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: emp-backend
    spec:
      containers:
        - env:
            - name: DEVOPS_IP
            - value: 34.123.127.88
            - name: SPRING_DATASOURCE_PASSWORD
            - value: root
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://34.118.229.236:3306/employee_management?autoReconnect=true
            - name: SPRING_DATASOURCE_USERNAME
            - value: root
          image: khanster/emp-backend:latest
          name: emp-backend
          ports:
            - containerPort: 8020
              protocol: TCP
      restartPolicy: Always
