apiVersion: v1
kind: Service
metadata:
  labels:
    app: emp-backend
  name: emp-backend
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8020
      targetPort: 8020
  selector:
    io.kompose.service: emp-backend
