apiVersion: v1
kind: Service
metadata:
  labels:
    app: emp-backend
  name: emp-backend
spec:
  type: LoadBalancer
  clusterIP: 10.96.0.13
  externalIPs:
    - 192.168.0.13
  externalTrafficPolicy: Local
  ports:
    - name: "8020"
      port: 8020
      targetPort: 8020
  selector:
    app: emp-backend
